- hosts: localhost
  connection: local
  vars:
  tasks:
# ansible community.general.homebrew module
# https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html
# homebrew
    - name: brew update
      community.general.homebrew:
        update_homebrew: yes
    - name: brew upgrade
      community.general.homebrew:
        upgrade_all: yes
    - name: brew install
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - emacs
        - fzf
        - git
        - tmux
        - asdf
        - mas
        - tree
        - gh
        - ghq
        - visual-studio-code
        - visual-studio-code@insiders
        - google-chrome
        - firefox
        - spotify
        - slack
        - docker
        - karabiner-elements
# ssh
    - name: make .ssh dir
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
    - name: generate ssh keys
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519
# ansilbe community.general.osx_defaults module
# https://docs.ansible.com/ansible/latest/collections/community/general/osx_defaults_module.html
# dock
    - name: orientation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: left
    - name: hide
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
# finder
    - name: status bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowStatusBar
        type: bool
        value: true
    - name: path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathbar
        type: bool
        value: true
