- hosts: localhost
  connection: local
  vars:
  tasks:
# homebrew
# community.general.homebrew module
# https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html
    - name: brew update
      community.general.homebrew:
        update_homebrew: yes
    - name: brew upgrade
      community.general.homebrew:
        upgrade_all: yes
    - name: brew install
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - asdf
        - chatgpt
        - claude
        - ctop
        - emacs
        - firefox
        - fzf
        - git
        - gh
        - ghostty
        - ghq
        - google-chrome
        - google-drive
        - htop
        - kap
        - karabiner-elements
        - logi-options+
        - mas
        - obsidian
        - rustup
        - slack
        - spotify
        - tmux
        - tree
        - visual-studio-code
        - visual-studio-code@insiders
        - zed
        - zsh-completions
# homebrew cask
# community.general.homebrew_cask module
# https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_cask_module.html
    - name: brew install cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - rectangle
# ssh
    - name: make .ssh dir
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
    - name: generate ssh keys
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519
# osx_defaults
# community.general.osx_defaults module
# https://docs.ansible.com/ansible/latest/collections/community/general/osx_defaults_module.html
# dock
    - name: orientation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: left
    - name: hide
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
# finder
    - name: status bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowStatusBar
        type: bool
        value: true
    - name: path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathbar
        type: bool
        value: true
# mas
# community.general.mas module
# https://docs.ansible.com/ansible/latest/collections/community/general/mas_module.html
    - name: install kindle
      community.general.mas:
        id: 302584613
        state: present
# misc
    - name: clone dotfiles repo
      ansible.builtin.git:
        repo: git@github.com:sakihet/dotfiles.git
        dest: ~/src/github.com/sakihet/dotfiles
