- hosts: localhost
  connection: local
  vars:
    node_version: 10.16.3
    ruby_version: 2.6.4
  tasks:

  - name: brew update
    homebrew:
      update_homebrew: yes

  - name: brew upgrade
    homebrew:
      upgrade_all: yes

  - name: brew tap
    homebrew_tap:
      tap: "{{ item }}"
      state: present
    loop:
      - homebrew/cask
      - homebrew/cask-versions

  - name: brew cask install
    homebrew_cask:
      name: "{{ item }}"
      state: present
    loop:
      - java8

  - name: brew install
    homebrew:
      name: "{{ item }}"
      state: present
    loop:
      - ansible
      - coreutils
      - emacs
      - ghq
      - git
      - go
      - heroku/brew/heroku
      - hugo
      - jq
      - nodenv
      - mas
      - mysql
      - peco
      - postgresql
      - rbenv
      - redis
      - ruby-build
      - sbt
      - tig
      - tmux
      - tree
      - zsh
      - zsh-completions

  - name: check node version
    shell: node --version
    register: user_node_version
    ignore_errors: yes

  - name: show node version
    debug:
      var: user_node_version.stdout

  - name: install node & set global node version
    shell: nodenv install {{ node_version }} && nodenv global {{ node_version }}
    when: user_node_version.stdout is not search(node_version)

  - name: check ruby version
    shell: ruby --version
    register: user_ruby_version
    ignore_errors: yes

  - name: show ruby version
    debug:
      var: user_ruby_version.stdout

  - name: install ruby & set global ruby version
    shell: rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }}
    when: user_ruby_version.stdout is not search(ruby_version)

  - name: brew cask install
    ignore_errors: yes
    homebrew_cask:
      name: "{{ item }}"
      state: present
    loop:
      - atom
      - dash
      - discord
      - docker
      - dropbox
      - enpass
      - evernote
      - firefox
      - github
      - google-chrome
      - intellij-idea-ce
      - iterm2
      - kap
      - karabiner-elements
      - notion
      - sequel-pro
      - slack
      - spectacle
      - vagrant
      - virtualbox
      - visual-studio-code
      - wordpresscom
    tags:
      - cask

  - name: install gem
    gem:
      name: tmuxinator
      state: latest

  - name: install npm
    npm:
      name: '@vue/cli'
      state: latest
      global: yes

  - name: enable debug on safari
    osx_defaults:
      domain: com.apple.Safari
      key: IncludeInternalDebugMenu
      type: bool
      value: true
      state: present

  - name: dock orientation
    osx_defaults:
      domain: com.apple.dock
      key: orientation
      type: string
      value: left

  - name: finder status bar
    osx_defaults:
      domain: com.apple.finder
      key: ShowStatusBar
      type: bool
      value: true

  - name: finder path bar
    osx_defaults:
      domain: com.apple.finder
      key: ShowPathbar
      type: bool
      value: true

  - name: clone dotfiles
    git:
      repo: git@github.com:sakihet/dotfiles.git
      dest: ~/src/github.com/sakihet/dotfiles

  - name: clone .atom
    git:
      repo: git@github.com:sakihet/.atom.git
      dest: ~/src/github.com/sakihet/.atom

  - name: clone .emacs.d
    git:
      repo: git@github.com:sakihet/.emacs.d.git
      dest: ~/src/github.com/sakihet/.emacs.d
