- hosts: localhost
  connection: local
  vars:
    node_version: 8.11.1
    ruby_version: 2.5.1
  tasks:

  - name: brew update
    homebrew:
      update_homebrew: yes

  - name: brew upgrade
    homebrew:
      upgrade_all: yes

  - name: brew tap
    homebrew_tap: tap={{ item }}
    state: present
    with_items:
      - caskroom/cask
      - caskroom/versions

  - name: brew cask install
    homebrew_cask: name={{ item }}
    state: present
    with_items:
      - java8

  - name: brew install
    homebrew: name={{ item }}
    state: present
    with_items:
      - ansible
      - coreutils
      - emacs
      - ghq
      - git
      - go
      - jq
      - nodenv
      - mas
      - mysql
      - peco
      - rbenv
      - redis
      - ruby-build
      - sbt
      - tmux
      - tree
      - zsh
      - zsh-completions

  - name: check node version
    shell: node --version
    register: user_node_version
    ignore_errors: yes

  - name: show node version
    debug:
      var: user_node_version.stdout

  - name: install node & set global node version
    shell: nodenv install {{ node_version }} && nodenv global {{ node_version }}
    when: user_node_version.stdout is not search(node_version)

  - name: check ruby version
    shell: ruby --version
    register: user_ruby_version
    ignore_errors: yes

  - name: show ruby version
    debug:
      var: user_ruby_version.stdout

  - name: install ruby & set global ruby version
    shell: rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }}
    when: user_ruby_version.stdout is not search(ruby_version)

  - name: brew cask install
    homebrew_cask: name={{ item }}
    state: present
    with_items:
      - atom
      - dash
      - discord
      - dropbox
      - enpass
      - evernote
      - firefox
      - github
      - google-chrome
      - intellij-idea-ce
      - iterm2
      - kap
      - karabiner-elements
      - sequel-pro
      - skitch
      - slack
      - spectacle
      - tweeten
      - vagrant
      - virtualbox
      - visual-studio-code
      - wordpresscom

  - name: enable debug on safari
    osx_defaults:
      domain: com.apple.Safari
      key: IncludeInternalDebugMenu
      type: bool
      value: true
      state: present

  - name: clone dotfiles
    git:
      repo: git@github.com:sakihet/dotfiles.git
      dest: ~/src/github.com/sakihet/dotfiles

  - name: clone .atom
    git:
      repo: git@github.com:sakihet/.atom.git
      dest: ~/src/github.com/sakihet/.atom

  - name: clone .emacs.d
    git:
      repo: git@github.com:sakihet/.emacs.d.git
      dest: ~/src/github.com/sakihet/.emacs.d
