- hosts: localhost
  connection: local
  tasks:
  - name: brew update
    homebrew:
      update_homebrew=yes
  - name: brew install
    homebrew: name={{ item }}
    state: present
    with_items:
      - ansible
      - coreutils
      - emacs
      - ghq
      - git
      - go
      - node
      - mas
      - peco
      - rbenv
      - ruby-build
      - tmux
      - tree
      - zsh
      - zsh-completions
  - name: brew tap
    homebrew_tap: tap={{ item }}
    state: present
    with_items:
      - caskroom/cask
  - name: brew cask install
    homebrew_cask: name={{ item }}
    state: present
    with_items:
      - atom
      - dash
      - discord
      - dropbox
      - enpass
      - firefox
      - google-chrome
      - iterm2
      - karabiner-elements
      - spectacle
      - visual-studio-code
      - wordpresscom
  - name: enable debug on safari
    osx_defaults:
      domain: com.apple.Safari
      key: IncludeInternalDebugMenu
      type: bool
      value: true
      state: present
  - name: clone dotfiles
    git:
      repo: git@github.com:sakihet/dotfiles.git
      dest: ~/src/github.com/sakihet/dotfiles
  - name: clone .atom
    git:
      repo: git@github.com:sakihet/.atom.git
      dest: ~/src/github.com/sakihet/.atom
  - name: clone .emacs.d
    git:
      repo: git@github.com:sakihet/.emacs.d.git
      dest: ~/src/github.com/sakihet/.emacs.d
